config/routes.rb
Metatest::Application.routes.draw do
  resources :tweets

  resources :twitter_accounts do 
    resources :tweets
  end

end

app/models/facebook_post.rb
class FacebookPost < ActiveRecord::Base
  def linked_body
    self.body.gsub(/@[0-9A-Za-z_]+/) do |capture|
      "<a href = '#{capture}'>#{capture}</a>"
    end
  end
end

app/models/flickr_post.rb
class FlickrPost < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :twitter_account

  def linked_body
    self.body.gsub(/@[0-9A-Za-z_]+/) do |capture|
      "<a href = '#{capture}'>#{capture}</a>"
    end
  end
end

app/models/twitter_account.rb
class TwitterAccount < ActiveRecord::Base
  include TwitterClient

  has_many :tweets
  after_save :import_tweets

  def import_tweets
    twitter_client.user_timeline(self.handle).each do |api_tweet|
      tweet = Tweet.new
      tweet.body = api_tweet.text
      tweet.external_id = api_tweet.id 
      self.tweets << tweet unless self.tweets.exists?(external_id: api_tweet.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :set_twitter_account, only: [:show, :edit, :update, :destroy]

  def index
    @twitter_accounts = TwitterAccount.all 
  end

  def show
    @tweets = @twitter_account.tweets.limit(10)
  end

  def new
    @twitter_account = TwitterAccount.new
  end

  def create
    @twitter_account = TwitterAccount.new(twitter_account_params)

    respond_to do |format|
      if @twitter_account.save
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully created' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @twitter_account.save
        format.html { redirect_to @twitter_account, notice: 'Twitter account was successfully created' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @twitter_account.destroy
    respond_to do |format|
      format.html { redirect_to twitter_accounts_url }
    end
  end

  private 

  def set_twitter_account
    @twitter_account = TwitterAccount.find(params[:id])
  end

  def twitter_account_params
    params.require(:twitter_account).permit(:handle)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metatest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/twitter_accounts/_form.html.erb
<%= form_for(@twitter_account) do |f| %>
  <% if @twitter_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter_account.errors.count, "error") %> prohibited this twitter_account from being saved:</h2>

      <ul>
      <% @twitter_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :handle %><br>
    <%= f.text_field :handle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twitter_accounts/edit.html.erb
<h1>Editing twitter_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter_account %> |
<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/index.html.erb
<h1>Listing Twitter Accounts</h1>
<table>
  <thead>
    <tr>
      <th>Handle</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @twitter_accounts.each do |twitter_account| %>
      <tr>
        <td><%= twitter_account.handle %></td>
        <td><%= link_to 'Show', twitter_account %></td>
        <td><%= link_to 'Edit', edit_twitter_account_path(twitter_account) %></td>
        <td><%= link_to 'Destroy', twitter_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Twitter account', new_twitter_account_path %>

app/views/twitter_accounts/new.html.erb
<h1>New twitter_account</h1>

<%= render 'form' %>

<%= link_to 'Back', twitter_accounts_path %>

app/views/twitter_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Showing Tweets For:</strong>
  <%= @twitter_account.handle %>
</p>

<ul>
  <% @tweets.each do |tweet| %>
    <li><%=@twitter_account.handle%>: <%=tweet.body%></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_twitter_account_path(@twitter_account) %> |
<%= link_to 'Back', twitter_accounts_path %>